version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: srv-captain--backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
  
  frontend:
    build: ./frontend
    container_name: srv-captain--frontend
    ports:
      - '80:80'
    depends_on:
      - backend
